export const members=[
    {
        name:'Nayeon',
        img:'/assets/imgs/members/tfNayeon.jpg',
        birthName:['Im Nayeon','임나연'],
        birthday:'September 22, 1995',
        position:['Lead Vocalist','Lead Dancer','Center','Eldest'],
        zodiac:'Vigro',
        blood:'A',
        nationality:'Korean',
        mbti:'ISFP',
        instagram: "https://www.instagram.com/nayeonyny",
    },
    {
        name:'Jeongyeon',
        img:'/assets/imgs/members/tfJY.jpg',
        birthName:['Yoo Jeongyeon','유정연'],
        birthday:'November 1, 1996',
        position:['Lead Vocalist'],
        zodiac:'Scorpio',
        blood:'O',
        nationality:'Korean',
        mbti:'ISFJ',
        instagram: "https://www.instagram.com/jy_piece",
    },
    {
        name:'Momo',
        img:'/assets/imgs/members/tfMM.jpg',
        birthName:['Hirai Momo','平井 もも'],
        birthday:'November 9, 1996',
        position:['Main Dancer','Sub Vocalist','Sub Rapper'],
        zodiac:'Scorpio',
        blood:'A',
        nationality:'Japanese',
        mbti:'INFP',
        instagram: "https://www.instagram.com/momo",
    },
    {
        name:'Sana',
        img:'/assets/imgs/members/tfSana.jpg',
        birthName:['Minatozaki Sana','湊崎 紗夏'],
        birthday:'December 29, 1996',
        position:['Sub Vocalist'],
        zodiac:'Capricon',
        blood:'B',
        nationality:'Japanese',
        mbti:'ENFP',
        instagram: "https://www.instagram.com/m.by__sana",
    },
    {
        name:'Jihyo',
        img:'/assets/imgs/members/tfJH.jpg',
        birthName:['Park Jihyo','박지효'],
        birthday:'February 1, 1997',
        position:['Leader','Main Vocalist'],
        zodiac:'Aquarius',
        blood:'O',
        nationality:'Korean',
        mbti:'ESFP',
        instagram: "https://www.instagram.com/_zyozyo",
    },
    {
        name:'Mina',
        img:'/assets/imgs/members/tfMN.jpg',
        birthName:['Myoui Mina','名井 南'],
        birthday:'March 24, 1997',
        position:['Main Dancer','Sub Vocalist'],
        zodiac:'Aries',
        blood:'A',
        nationality:'Japanese',
        mbti:'ISTP',
        instagram: "https://www.instagram.com/mina_sr_my",
    },
    {
        name:'Dahyun',
        img:'/assets/imgs/members/tfDH.jpg',
        birthName:['Kim Dahyun','김다현'],
        birthday:'May 28, 1998',
        position:['Lead Rapper','Sub Vocalist'],
        zodiac:'Gemini',
        blood:'O',
        nationality:'Korean',
        mbti:'ISFJ',
        instagram: "https://www.instagram.com/dahhyunnee",
    },
    {
        name:'Chaeyoung',
        img:'/assets/imgs/members/tfCY.jpg',
        birthName:['Son Chaeyoung','손채영'],
        birthday:'April 23, 1999',
        position:['Main Rapper','Sub Vocalist'],
        zodiac:'Taurus',
        blood:'O',
        nationality:'Korean',
        mbti:'INFP',
        instagram: "https://www.instagram.com/chaeyo.0",
    },
    {
        name:'Tzuyu',
        img:'/assets/imgs/members/tfTZ.jpg',
        birthName:['Chou Tzuyu','周子瑜'],
        birthday:'June 14, 1999',
        position:['Lead Dancer','Sub Vocalist','Visual','Maknae'],
        zodiac:'Gemini',
        blood:'A',
        nationality:'Taiwanese',
        mbti:'ISFP',
        instagram: "https://www.instagram.com/thinkaboutzu",
    },
    
]